# general configuration
url: http://hound.media
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/assets/mediaHoundDog.svg"
  # author will appear under the avatar (optional)
  author: "Hound CLI"

  creator: "MediaHound"

  description: "Find media from the command line"
  
  # tagline will appear under the title (optional)
  # tagline: "Find media from the command line"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true
