# general configuration
url: http://hound.media
baseurl: ''

# compass configuration
compass:
  logo: "/assets/mediaHoundDog.svg"
  author: "Hound CLI"
  creator: "MediaHound"
  description: "Find media from the command line"
  include_content: true
  include_analytics: true

# Dependencies
markdown: kramdown
highlighter: pygments

# Markdown Configuration
kramdown:
  input: GFM

# Permalinks
permalink: pretty
relative_permalinks: true
